config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"
  mount Messenger::Bot::Space => "/webhook"

  post 'journey', to: 'pages#journey'

  resources :orders, only: [:show, :new, :create] do
    # member do
    #   get 'payment', to: 'orders#payment'
    # end
    resources :addresses, only: [:new, :create]
  end
  # Order-items are within the order, does not need own path
  resources :plants, only: [:index, :show] do
    resources :order_items, only: [:create, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders, only: [:show, :create] do
  resources :payments, only: [:new, :create]
  end
end

app/views/shared/_cart.js.erb
jQuery(document).ready(function($){
  $menu_navigation = $('#main-nav'),
  $cart_trigger = $('#shopping-cart-closed'),
  $cart_opened = $('#shopping-cart-opened'),
  $lateral_cart = $('#cart-summary'),
  $shadow_layer = $('<div id="shadow-layer">');


  $cart_trigger.click(function() {
    var shadow_layer = $('<div id="shadow-layer">');
    $('body').append(shadow_layer);
    shadow_layer.fadeIn();
    $('body').animate({"margin-right": "280px"}, "fast");
    $lateral_cart.fadeIn();
    $cart_opened.fadeIn();
    $cart_trigger.hide();
    shadow_layer.click(function() {
      $(this).fadeOut("fast", function() { $(this).remove(); });
      $('body').animate({"margin-right": "0"}, "fast");
      $lateral_cart.fadeOut();
      $cart_opened.fadeOut();
      $cart_trigger.show();
    });
  })
});

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

<div id="custom-flash" class="alert alert-info alert-dismissible" role="alert" hidden="true">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <div id="custom-alert-text"></div>
</div>

app/views/shared/_footer.html.erb
<div class="footer" id="footer">
  <div class="footer-links">
    <%= link_to("https://www.facebook.com/sproutmtl") do %>
      <i class="fa fa-facebook"></i>
    <% end %>
  </div>
  <div class="footer-copyright">
  This website is made with <i class="fa fa-heart"></i> by Team Sprout
  at Le Wagon.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon" id="main-nav">
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-left navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
    <span class="navbar-title">sprout</span>
  <% end %>
  <div class="navbar-right">
    <div id="navbar-plants" class="navbar-wagon-item navbar-wagon-link">
      <%= link_to 'Plants', plants_path %>
    </div>
    <div id="navbar-shopping-cart">
      <%= render "components/shopping_cart", cart_id: 'shopping-cart-closed', hidden: "", on_click: "" %>
    </div>
  </div>
  <!-- Right Navigation -->
      <!-- Login link (when logged out) -->
    <!-- shopping cart logo -->

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
  <!-- cart summary appear -->
  <div class="navbar-cart-summary", id="cart-summary">
    <div class="shopping-cart-icon">
      <%= render "components/shopping_cart", cart_id: 'shopping-cart-opened', hidden: "hidden", on_click: "on-click"  %>
    </div>
    <div class="navbar-cart-content">
      <div class="navbar-cart-scroll" id="cart-summary-content">
        <%= render "orders/mini_cart", order_items: current_order.order_items %>
      </div>
    </div>
    <div class="navbar-cart-footer">
      SUB-TOTAL
      <span id="cart-summary-total">$ <%= number_with_precision(current_order.subtotal, :precision => 2) %></span>
    </div>
    <%= link_to "CHECKOUT", new_order_path, class: "checkout-btn" %>
  </div>
</div>

<script>
  <%= render 'shared/cart.js.erb' %>
</script>

app/views/shared/_plants.html.erb
<div class="card-container">
  <%= link_to plant_path(plant) do %>
    <div class="card-img" style="background-image: url('<%= cl_image_path plant.photo && plant.photo.path || '/' %>'); height: <%= height %>;">
      <div class="card-content">
        <div class="card-item card-name ">
          <h2><%= plant.common_name %></h2>
        </div>
        <div class="card-item card-price">
          <p><%= plant.price %></p>
        </div>
        <div class="card-item card-info">
          <ul>
            <li>
              <i class="fa fa-sun-o" aria-hidden="true"></i>
              <p><%= plant.sun_level %></p>
            </li>
            <li>
              <i class="fa fa-tint" aria-hidden="true"></i>
              <p><%= plant.water_level %></p>
            </li>
            <li>
              <i class="fa fa-heart" aria-hidden="true"></i>
              <p><%= plant.care_level %></p>
            </li>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>