config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"
  mount Messenger::Bot::Space => "/webhook"

  post 'journey', to: 'pages#journey'

  resources :orders, only: [:show, :new, :create] do
    # member do
    #   get 'payment', to: 'orders#payment'
    # end
    resources :addresses, only: [:new, :create]
  end
  # Order-items are within the order, does not need own path
  resources :plants, only: [:index, :show] do
    resources :order_items, only: [:create, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders, only: [:show, :create] do
  resources :payments, only: [:new, :create]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :plants, through: :order_items
  has_one :address, through: :user

  before_create :set_order_status
  before_save :update_subtotal
  # validates :address, presence: true
  # monetize :amoun


  def num_of_items
    order_items.collect { |oi| oi.valid? ? oi.quantity : 0 }.sum
  end

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  def shipping
    15 # 15$ shipping for all orders
  end

  def tax
    subtotal * 0.15
  end

  def total
    order_items.collect { |oi| oi.valid? ? oi.total_price : 0 }.sum + shipping + tax
  end



  def show_status
    case self[:status]
    when 3
      "Completed"
    when 1
      "Placed"
    when 2
      "Shipped"
    else
      "Pending"
    end
  end

  private

  def set_order_status
    self[:status] = 0
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @order_items = current_order.order_items
    @order = Order.where(state: 'paid').find(params[:id])
  end

  def new
    @address = Address.new
  end

  def create
    @order = Order.new(current_order)
    @order.status = "pending"
    @order.user = current_user
    @order.address = current_user.address
    @order.shipping
    @order.tax
    @order.save!

    redirect_to new_order_payment_path(order)
  end

  private

  # def order_params
  #   params.require(:order).permit(:subtotal, :shipping, :tax, :total)
  # end
end

app/views/orders/_cart_table.html.erb
<table id="cart-table" class="item-list">
  <thead>
    <tr>
      <th class="section-header th-delete"></th>
      <th class="section-header th-img"></th>
      <th class="section-header">PLANT</th>
      <th class="section-header">PRICE</th>
      <th class="section-header">QTY</th>
      <th class="section-header">TOTAL</th>
    </tr>
  </thead>
  <tbody>
    <% order_items.each do |oi| %>
      <tr class="cart-row">
        <td class="item-details">
          <div class="item-delete">
            <%= link_to plant_order_item_path(oi.plant, oi), method: :delete do %>
              <i class="fa fa-times" aria-hidden="true"></i>
            <% end %>
          </div>
        </td>
        <td class="item-details">
          <div class="item-image">
            <%= cl_image_tag oi.plant.photo.path, width: 200, height: 300, crop: :fill %>
          </div>
        </td>
        <td class="item-details">
          <div class="item-name">
            <%= oi.plant.common_name %>
          </div>
        </td>
        <td class="item-details">
          <div class="item-price">
            $ <%= oi.unit_price %>
          </div>
        </td>
        <td class="item-details">
          <div class="item-qty">
            <%= oi.quantity %>
          </div>
        </td>
        <td class="item-details">
          <div class="item-total">
            $ <%= oi.total_price %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/_mini_cart.html.erb
<% order_items.each do |oi| %>
  <div data-order-item-id="<%= oi.id %>">
    <div class="mini-cart">
      <div class="mini-cart-image">
        <%= cl_image_tag oi.plant.photo.path, height: 150, crop: :fill %>
      </div>
      <div class="mini-cart-content">
        <h3><%= oi.plant.common_name.upcase %></h3>
        <p>QTY: <%= oi.quantity %></p>
        <%= link_to plant_order_item_path(oi.plant, oi), method: :delete, remote: true do %>
          <i class="fa fa-times" aria-hidden="true"></i>
        <% end %>
        <h4>$ <%= number_with_precision(oi.total_price, :precision => 2) %></h4>
      </div>
    </div>
  </div>
<% end %>

app/views/orders/_order_totals_table.html.erb
<table class="order-totals-table">
  <tbody>
    <tr class="order-subtotal">
      <td>Subtotal</td>
      <td>$ <%= number_with_precision(order.subtotal, :precision => 2) %></td>
    </tr>
    <tr class="order-shipping">
      <td>Shipping</td>
      <td>
        $ <%= number_with_precision(order.shipping, :precision => 2) %>
      </td>
    </tr>
    <tr class="order-sales-tax">
      <td>Tax</td>
      <td>
          $ <%= number_with_precision(order.tax, :precision => 2) %>
      </td>
    </tr>
    <tr class="order-total">
      <td>Total</td>
      <td class="order-value">$ <%= number_with_precision(order.total, :precision => 2) %></td>
    </tr>
  </tbody>
</table>

app/views/orders/_payment_form.html.erb
<%= form_tag order_payments_path(order) do %>
  <article>
    <label class="amount">
      <span>Final amount to be charged: <%= humanized_money_with_symbol(order.total) %></span>
    </label>
  </article>
<% end %>

<script src="https://js.stripe.com/v3/"></script>
  <form action="/charge" method="post" id="payment-form">
    <div class="form-row">
      <label for="card-element">
        Pay with your credit card via Stripe. <%= image_tag("Visa-Master-Card.png", height: 25) %>
      </label>
      <div id="card-element">
        <!-- a Stripe Element will be inserted here. -->
      </div>

      <!-- Used to display form errors -->
      <div id="card-errors" role="alert"></div>
    </div>
  </form>
<script type="text/javascript">

  // Create a Stripe client
  var stripe = Stripe('pk_test_mQ4nEfJvIIfBzwjFNIrmAllN');
  // Create an instance of Elements
  var elements = stripe.elements();
  // Custom styling can be passed to options when creating an Element.
  // (Note that this demo uses a wider set of styles than the guide below.)
  var style = {
    base: {
      color: '#32325d',
      lineHeight: '18px',
      fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
      fontSmoothing: 'antialiased',
      fontSize: '16px',
      '::placeholder': {
        color: '#aab7c4'
      }
    },
    invalid: {
      color: '#fa755a',
      iconColor: '#fa755a'
    }
  };
  // Create an instance of the card Element
  var card = elements.create('card', {style: style});

  // Add an instance of the card Element into the `card-element` <div>
  card.mount('#card-element');
  // Handle real-time validation errors from the card Element.
  card.addEventListener('change', function(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
  });
  // Handle form submission
  var form = document.getElementById('payment-form');
  form.addEventListener('submit', function(event) {
    event.preventDefault();

    stripe.createToken(card).then(function(result) {
      if (result.error) {
        // Inform the user if there was an error
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        // Send the token to your server
        stripeTokenHandler(result.token);
      }
    });
  });
</script>

app/views/orders/new.html.erb
<div class="leaves-background col-sm-12">
<div class="container">
  <div class="row">
    <h1 class="title-1">CHECKOUT</h1>
  </div>
  <div class="row">
    <div class="checkout-container">
      <div class="checkout-steps">
        <div class="checkout-step active" id="step-1">
          <h4 class="title-3">Shipping</h4>
        </div>
        <div class="checkout-step" id="step-2">
          <h4 class="title-3">Payment</h4>
        </div>
        <div class="checkout-step" id="step-3">
          <h4 class="title-3">Confirmation</h4>
        </div>
      </div>
      <div class="checkout-form form-login" id="address-form">
        <h3 class="title-2">Enter Shipping Address</h3>
        <%= render "addresses/form", address: @address, order: current_order %>
        <button class="sprout-btn sprout-cta" id="payment-btn">Continue to Payment</button>
      </div>
      <div class="checkout-form form-login hidden" id="payment-form">
        <h3 class="title-2">Enter Payment Information</h3>
        <%= render "payment_form", order: current_order %>
        <button class="sprout-btn sprout-cta" id="order-btn">Order</button>
      </div>
      <div class="checkout-form form-login hidden" id="order-form">
          <h3> Thanks for shopping with us, <%= current_user[:first_name] %>! </h3>
          <h4> Your order will arrive in up to 5 business days and will be shipped to: </h4>
          <br>
          <div class="order-confirmation-details">
            <div class="address-details">
              <h5 id="street"><%= current_order.address[:street_address].titleize rescue "" %>. </h5>
              <h5 id="city-country"><%= current_order.address[:city].titleize rescue ""  %>, <%= current_order.address[:country].titleize  rescue "" %></h5>
              <h5 id="postal"><%= current_order.address[:postal_code].upcase rescue ""  %></h5>
            </div>
            <div class="messenger-reminders">
              <h5>Get watering reminders with messenger:</h5>
              <div class="fb-send-to-messenger"
               messenger_app_id=<%= ENV['FB_APP_ID'] %>
               page_id= <%= ENV['FB_PAGE_ID'] %>
               data-ref= <%= current_user.id %>
               color="blue"
               size="xlarge">
              </div>
            </div>
          </div>
      </div>
      <div class="order-summary">
          <h4 class="order-header title-2">Order Summary</h4>
        <div class="order-summary-box">
          <div class="box-card">
            <%= render 'mini_cart', order_items: current_order.order_items %>
          </div>
          <%= render 'order_totals_table', order: current_order %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<%= content_for(:after_js) do%>
  <script>
      window.fbAsyncInit = function() {
     FB.init({
     appId: <%= ENV['FB_APP_ID'] %>,
     xfbml: true,
     version: "v2.6"
     });

     FB.Event.subscribe('send_to_messenger', function(e) {
     // callback for events triggered by the plugin

     });

     };

     (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) { return; }
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));

    // checkout flow
    paymentBtn = document.getElementById("payment-btn");
    paymentBtn.addEventListener('click', (event) => {
    console.log('/orders/<%= current_order.id%>/addresses');
      let data = { address: {
                  street_address: $('#address_street_address').val(),
                  city: $('#address_city').val(),
                  country: $('#address_country').val(),
                  postal_code: $('#address_postal_code').val(),
                  phone_number: $('#address_phone_number').val(),
                  first_name: $('#address_first_name').val(),
                  last_name: $('#address_last_name').val()
                  } }
        $.ajax({
         url: '/orders/<%= current_order.id%>/addresses',
         data,
         type: 'POST'
        });

      document.getElementById("street").innerHTML = data.address.street_address;
      document.getElementById("city-country").innerHTML = data.address.city + ", " + data.address.city;
      document.getElementById("postal").innerHTML = data.address.postal_code.toUpperCase();

      orderBtn = document.getElementById("order-btn");
      paymentForm = document.getElementById("payment-form");
      orderForm = document.getElementById("order-form");
      step2 = document.getElementById("step-2");
      step3 = document.getElementById("step-3");
      orderBtn.addEventListener('click', (event) => {
        paymentForm.classList.add("hidden");
        orderForm.classList.remove("hidden");
        step2.classList.remove("active");
        step3.classList.add("active");
      })
    });
  </script>
<% end %>

app/views/orders/show.html.erb
<h2>Your Order</h2>
<%= link_to "Checkout", new_order_path %>
<%= render 'cart_table', order_items: @order_items %>
<div class="cart-footer">
  <div class="cart-order-totals">
    <%= render 'order_totals_table', order: current_order %>
  </div>
</div>